apiVersion: v1
kind: Namespace
metadata:
  name: istio-system
  labels:
    name: istio-system
---
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: istio-control-plane
spec:
  profile: demo
  components:
    ingressGateways:
    - enabled: true
      name: istio-ingressgateway
      k8s:
        service:
          type: NodePort
  meshConfig:
    accessLogFile: /dev/stdout
    enableTracing: true
    defaultConfig:
      tracing:
        sampling: 100
  values:
    global:
      tracer:
        zipkin:
          address: otel-collector.istio-system:9411
