apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-conf
  namespace: istio-system
  labels:
    app: opentelemetry
    component: otel-collector-conf
data:
  otel-collector-config: |
    receivers:
      zipkin:
        endpoint: 0.0.0.0:9411
      otlp:
        protocols:
          grpc:
          http:
      jaeger:
        protocols:
          grpc:

    processors:
      batch:

    exporters:
      humio:
        endpoint: "https://cloud.humio.com/"
        insecure_skip_verify: true
        tag: service_name
        traces:
          ingest_token: ${HUMIO_INGEST_TOKEN_TRACES}
          unix_timestamps: true
        sending_queue:
          enabled: true
          num_consumers: 20
          queue_size: 2500
        retry_on_failure:
          enabled: true
          initial_interval: 8s
          max_interval: 2m
          max_elapsed_time: 5m
      logging:

    extensions:
      health_check:
      pprof:
      zpages:
        endpoint: :55679

    service:
      extensions: [health_check,pprof,zpages]
      pipelines:
        traces/1:
          receivers: [zipkin,otlp,jaeger]
          processors: [batch]
          exporters: [humio]
---
apiVersion: v1
kind: Service
metadata:
  name: otel-collector
  namespace: istio-system
  labels:
    app: opentelemetry
    component: otel-collector
spec:
  ports:
  - name: otlp # Default endpoint for OpenTelemetry receiver.
    port: 4317
  - name: zipkin # Default endpoint for Zipkin receiver.
    port: 9411
  - name: metrics # Default endpoint for querying metrics.
    port: 8888
  - name: jaeger # Default endpoint for Jaeger
    port: 14250
  selector:
    component: otel-collector
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel-collector
  namespace: istio-system
  labels:
    app: opentelemetry
    component: otel-collector
spec:
  selector:
    matchLabels:
      app: opentelemetry
      component: otel-collector
  minReadySeconds: 5
  progressDeadlineSeconds: 120
  replicas: 1
  template:
    metadata:
      labels:
        app: opentelemetry
        component: otel-collector
    spec:
      containers:
      - image: em135/collector-contrib:latest
        name: otel-collector
        imagePullPolicy: Always
        env:
        - name: HUMIO_INGEST_TOKEN_TRACES
          valueFrom:
            secretKeyRef:
              name: humio-secrets
              key: humio-ingest-token-traces
        resources:
          limits:
            cpu: '1'
            memory: 2Gi
          requests:
            cpu: 200m
            memory: 400Mi
        ports:
        - containerPort: 4317
        - containerPort: 9411
        - containerPort: 8888
        - containerPort: 13133
        - containerPort: 14250
        volumeMounts:
        - name: otel-collector-config-vol
          mountPath: /etc/config
        livenessProbe:
          httpGet:
            path: /
            port: 13133
        readinessProbe:
          httpGet:
            path: /
            port: 13133
      volumes:
        - configMap:
            name: otel-collector-conf
            items:
              - key: otel-collector-config
                path: otel-collector-config.yaml
          name: otel-collector-config-vol
