receivers:
  otlp:
    protocols:
      grpc:
      http:
  jaeger:
    protocols:
      grpc:

processors:
  batch:

exporters:
  humio:
    endpoint: "https://cloud.humio.com/"
    insecure_skip_verify: true
    tag: service_name
    traces:
      ingest_token: "${HUMIO_INGEST_TOKEN}"
      unix_timestamps: true
    sending_queue:
      enabled: true
      num_consumers: 20
      queue_size: 2500
    retry_on_failure:
      enabled: true
      initial_interval: 8s
      max_interval: 2m
      max_elapsed_time: 5m

extensions:
  health_check:
  pprof:
  zpages:
    endpoint: :55679

service:
  extensions: [health_check,pprof,zpages]
  pipelines:
    traces:
      receivers: [otlp,jaeger]
      processors: [batch]
      exporters: [humio]
