version: "3.5"

services:
    fluentd:
        image: xitric/fluentd:latest
        hostname: fluentd
        volumes:
          - .:/fluentd/etc
        ports:
          - 24224:24224
          - 24224:24224/udp
